services:
  test:
    image: node:18 # Image Docker de Node.js
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile.test # Spécifie le Dockerfile pour ce service
    depends_on:
      - postgres
      - mongodb
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    volumes:
      - .:/app # Monter le dossier local 'infrastructure' dans le conteneur à /app
    working_dir: /app # Définir le répertoire de travail à /app (qui contient ton code)
    command: ["npm", "test"] # Exécuter les tests via npm
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Port par défaut : 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-my_database}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017" # Port par défaut : 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
  mongo_data:
