# Utilisez une image de base Node.js
FROM node:18

# Créez un répertoire pour votre application dans le conteneur
WORKDIR /app

# Copiez le fichier package.json et package-lock.json (si présents)
COPY package*.json ./

# Installez les dépendances
RUN npm cache clean --force && npm install

# Copiez le reste de votre code source dans le conteneur
COPY . .

# Installez tous les outils nécessaires (par exemple, Jest, Mocha, etc.)
RUN npm install --save-dev jest

# Commande par défaut pour exécuter les tests
CMD ["npm", "test"]
