services:
  dev:
    image: node:18
    container_name: dev
    depends_on:
      - postgres
      - mongodb
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    volumes:
      - .:/app
    working_dir: /app
    # Installation des dépendances au démarrage
    command: >
      sh -c "npm install &&
             tail -f /dev/null"
    networks:
      - app_network

  nest-app:
    image: node:18
    container_name: nest-app
    depends_on:
      - postgres
      - mongodb
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      PORT: 3001
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "npx ts-node infrastructure/http/nest/main.ts"
    ports:
      - "3001:3001"
    networks:
      - app_network

  express-app:
    image: node:18
    container_name: express-app
    depends_on:
      - postgres
      - mongodb
      - nest-app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      PORT: 3000
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "npx ts-node infrastructure/http/express/server.ts"
    ports:
      - "3000:3000"
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Port par défaut : 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-my_database}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017" # Port par défaut : 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
  mongo_data:
